apiVersion: v1
kind: Service
metadata:
  name: bookapp-service
spec:
  selector:
    app: bookapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888

# kubectl port-forward service/bookapp-service 8888:80
# port forward